version: '3.8'

services:
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    container_name: micare_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRESQL_DB},${BOTPRESS_DB},mapseh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./multipledb:/docker-entrypoint-initdb.d
      - ./postgresql.conf:/db_config/postgresql.conf

  oidc:
    restart: unless-stopped
    depends_on:
      - postgres
    container_name: oidc
    image: keycloak/keycloak:${KEYCLOAK_VERSION}
    ports:
      - '8080:8080'
    env_file:
      - .env
    entrypoint: [
        '/opt/keycloak/bin/kc.sh',
        'start-dev',
        '--hostname-strict=false',
        '--features=declarative-user-profile',
        '--spi-theme-static-max-age=-1', # disable cache for theme customization
        '--spi-theme-cache-themes=false', # disable cache for theme customization
        '--spi-theme-cache-templates=false', # disable cache for theme customization
      ]
    volumes:
      - ./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./keycloak/themes:/opt/keycloak/themes
      - ./keycloak/quarkus.properties:/opt/keycloak/conf/quarkus.properties
    environment:
      KEYCLOAK_ADMIN: kcadmin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: 'jdbc:postgresql://postgres/keycloak'
      DB_DATABASE: ${POSTGRESQL_DB}
      KC_DB_USERNAME: ${POSTGRESQL_DB}
      KC_DB_PASSWORD: ${POSTGRESQL_PASS}
      VIRTUAL_PORT: '8080'
      PROXY_ADDRESS_FORWARDING: 'true'
